### PR TITLE
[Reports] Reports Claimed

### PR DESCRIPTION
**Pull request by SharkyTheKing**
This isn't finished yet, as I'm still going to be taking feedback from a specific user.

I still need to add cog disable system in here before I go forward with merge.

### CODE REVIEW

**Comment by SharkyTheKing** [comment]
Sharks an idiot and forgot to finish this. Heh. Sorry whoever was wanting this.

**Comment by J-Daniel-1** [comment]
Hey. Do you remember when I asked if the reactions had any purpose other than show? Is this merge adding purpose to those reactions? I do daily repo and cog updates and noticed the reports cog updating so that reminded me of the reactions having actions.

**Comment by SharkyTheKing** [comment]
Currently this is giving the ability to enable a "claim". So if a staff member reacts to the report, it'll edit the embed saying the moderator has claimed it!

**Comment by J-Daniel-1** [comment]
> 
> 
> Currently this is giving the ability to enable a "claim". So if a staff member reacts to the report, it'll edit the embed saying the moderator has claimed it!

Gotcha.

**Comment by SharkyTheKing** [comment]
I'll be pushing this forward soon, sorry for those waiting on this. I've been trying to work on multiple different projects that I've been wanting or for servers. Currently working on a huge project for a server that is due in the next few days. So going to try and get that done.

**Pull request merged**
